# Generated by Django 5.1.6 on 2025-03-17 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('localisation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='localisation',
            name='latitude',
            field=models.FloatField(blank=True, null=True, verbose_name='Latitude'),
        ),
        migrations.AlterField(
            model_name='localisation',
            name='longitude',
            field=models.FloatField(blank=True, null=True, verbose_name='Longitude'),
        ),
    ]
